export const LAYOUT = {
  SIDEBAR_WIDTH: 240,
  TOP_BAR_HEIGHT: 52,
  CONTENT_PADDING: 24,
} as const;

export const FONTS = {
  DISPLAY: "'Chakra Petch', sans-serif",
  BODY: "'IBM Plex Sans', sans-serif",
  MONO: "'IBM Plex Mono', monospace",
} as const;

// Color tokens resolve to CSS custom properties.
// Actual values are injected via <style> in Layout.tsx from DARK_THEME / LIGHT_THEME.
export const COLORS = {
  BG_PRIMARY: 'var(--c-bg-primary)',
  BG_SIDEBAR: 'var(--c-bg-sidebar)',
  BG_CARD: 'var(--c-bg-card)',
  BG_INPUT: 'var(--c-bg-input)',
  BG_HOVER: 'var(--c-bg-hover)',
  BG_ELEVATED: 'var(--c-bg-elevated)',

  BORDER: 'var(--c-border)',
  BORDER_LIGHT: 'var(--c-border-light)',

  TEXT_PRIMARY: 'var(--c-text-primary)',
  TEXT_HEADING: 'var(--c-text-heading)',
  TEXT_ACCENT: 'var(--c-text-accent)',
  TEXT_MUTED: 'var(--c-text-muted)',
  TEXT_DIM: 'var(--c-text-dim)',

  ACCENT: 'var(--c-accent)',
  ACCENT_DIM: 'var(--c-accent-dim)',
  ACCENT_GLOW: 'var(--c-accent-glow)',
  ACCENT_SECONDARY: 'var(--c-accent-secondary)',
  ACCENT_TERTIARY: 'var(--c-accent-tertiary)',

  TEAL: 'var(--c-teal)',
  TEAL_DIM: 'var(--c-teal-dim)',
  TEAL_GLOW: 'var(--c-teal-glow)',

  BUTTON: 'var(--c-button)',
  BUTTON_HOVER: 'var(--c-button-hover)',

  SUCCESS: 'var(--c-success)',
  ERROR: 'var(--c-error)',
  WARNING: 'var(--c-warning)',

  NAV_ACTIVE_BG: 'var(--c-nav-active-bg)',
  NAV_ACTIVE_BORDER: 'var(--c-nav-active-border)',

  GRADIENT_PRIMARY: 'var(--c-gradient-primary)',
  GRADIENT_SIDEBAR: 'var(--c-gradient-sidebar)',
  GRADIENT_HERO: 'var(--c-gradient-hero)',

  SHADOW_SM: 'var(--c-shadow-sm)',
  SHADOW_MD: 'var(--c-shadow-md)',
  SHADOW_GLOW: 'var(--c-shadow-glow)',
  SHADOW_TEAL: 'var(--c-shadow-teal)',

  TEXT_GLOW_AMBER: 'var(--c-text-glow-amber)',
  TEXT_GLOW_TEAL: 'var(--c-text-glow-teal)',

  BADGE_WAITING_BG: 'var(--c-badge-waiting-bg)',
  BADGE_WAITING_TEXT: 'var(--c-badge-waiting-text)',
  BADGE_ACTIVE_BG: 'var(--c-badge-active-bg)',
  BADGE_ACTIVE_TEXT: 'var(--c-badge-active-text)',
  BADGE_COMPLETED_BG: 'var(--c-badge-completed-bg)',
  BADGE_COMPLETED_TEXT: 'var(--c-badge-completed-text)',

  SURROGATE_BG: 'var(--c-surrogate-bg)',
  SURROGATE_TEXT: 'var(--c-surrogate-text)',
  SURROGATE_BORDER: 'var(--c-surrogate-border)',
  CONTRIBUTOR_BG: 'var(--c-contributor-bg)',
  CONTRIBUTOR_TEXT: 'var(--c-contributor-text)',
  CONTRIBUTOR_BORDER: 'var(--c-contributor-border)',
  OWN_MSG_BG: 'var(--c-own-msg-bg)',
  OTHER_MSG_BG: 'var(--c-other-msg-bg)',
} as const;

// --- Actual color values per theme ---

export const DARK_THEME: Record<string, string> = {
  'bg-primary': '#0a0a0f',
  'bg-sidebar': '#0d0d14',
  'bg-card': '#111118',
  'bg-input': '#0e0e15',
  'bg-hover': '#16161f',
  'bg-elevated': '#141420',
  'border': '#1e1e2a',
  'border-light': '#2a2a3a',
  'text-primary': '#d4c494',
  'text-heading': '#ffe0a6',
  'text-accent': '#FFB800',
  'text-muted': '#a89868',
  'text-dim': '#7a6e50',
  'accent': '#FFB800',
  'accent-dim': '#CC9200',
  'accent-glow': 'rgba(255,184,0,0.15)',
  'accent-secondary': '#00D4AA',
  'accent-tertiary': '#00D4AA',
  'teal': '#00D4AA',
  'teal-dim': '#00A888',
  'teal-glow': 'rgba(0,212,170,0.12)',
  'button': '#CC9200',
  'button-hover': '#FFB800',
  'success': '#00FF88',
  'error': '#FF4444',
  'warning': '#FFB800',
  'nav-active-bg': '#14141e',
  'nav-active-border': '#FFB800',
  'gradient-primary': 'linear-gradient(135deg, #CC9200, #FFB800)',
  'gradient-sidebar': 'linear-gradient(180deg, #0d0d14, #0a0a0f)',
  'gradient-hero': 'linear-gradient(135deg, #111118 0%, #141420 50%, #0d0d14 100%)',
  'shadow-sm': '0 2px 8px rgba(0,0,0,0.5)',
  'shadow-md': '0 4px 16px rgba(0,0,0,0.6)',
  'shadow-glow': '0 0 20px rgba(255,184,0,0.15)',
  'shadow-teal': '0 0 20px rgba(0,212,170,0.12)',
  'text-glow-amber': '0 0 8px rgba(255,184,0,0.35), 0 0 20px rgba(255,184,0,0.12)',
  'text-glow-teal': '0 0 8px rgba(0,212,170,0.3), 0 0 20px rgba(0,212,170,0.1)',
  'badge-waiting-bg': '#1a1500',
  'badge-waiting-text': '#FFB800',
  'badge-active-bg': '#001a10',
  'badge-active-text': '#00FF88',
  'badge-completed-bg': '#151518',
  'badge-completed-text': '#6a6670',
  'surrogate-bg': '#0a1418',
  'surrogate-text': '#80e0cc',
  'surrogate-border': '#1a2a2a',
  'contributor-bg': '#12101a',
  'contributor-text': '#b8a8d0',
  'contributor-border': '#2a2240',
  'own-msg-bg': '#1a1400',
  'other-msg-bg': '#111118',
  'grid-line': 'rgba(255,184,0,0.03)',
  'scan-line': 'rgba(0,0,0,0.04)',
  'vignette': 'rgba(0,0,0,0.4)',
  'data-readout-bg': 'rgba(255,184,0,0.06)',
};

export const LIGHT_THEME: Record<string, string> = {
  'bg-primary': '#f4efe4',
  'bg-sidebar': '#eae3d4',
  'bg-card': '#faf7f0',
  'bg-input': '#f0ebe0',
  'bg-hover': '#ede6d8',
  'bg-elevated': '#ffffff',
  'border': '#d4c8b0',
  'border-light': '#c0b49a',
  'text-primary': '#3a3020',
  'text-heading': '#2a1e10',
  'text-accent': '#996800',
  'text-muted': '#7a6a48',
  'text-dim': '#a89878',
  'accent': '#CC9200',
  'accent-dim': '#996800',
  'accent-glow': 'rgba(200,146,0,0.12)',
  'accent-secondary': '#008866',
  'accent-tertiary': '#008866',
  'teal': '#008866',
  'teal-dim': '#006644',
  'teal-glow': 'rgba(0,136,102,0.08)',
  'button': '#996800',
  'button-hover': '#CC9200',
  'success': '#00884c',
  'error': '#cc2222',
  'warning': '#CC9200',
  'nav-active-bg': '#f4efe4',
  'nav-active-border': '#CC9200',
  'gradient-primary': 'linear-gradient(135deg, #996800, #CC9200)',
  'gradient-sidebar': 'linear-gradient(180deg, #eae3d4, #e4dcc8)',
  'gradient-hero': 'linear-gradient(135deg, #faf7f0 0%, #f4efe4 50%, #eae3d4 100%)',
  'shadow-sm': '0 2px 8px rgba(0,0,0,0.06)',
  'shadow-md': '0 4px 16px rgba(0,0,0,0.08)',
  'shadow-glow': '0 0 20px rgba(200,146,0,0.1)',
  'shadow-teal': '0 0 20px rgba(0,136,102,0.08)',
  'text-glow-amber': 'none',
  'text-glow-teal': 'none',
  'badge-waiting-bg': '#fdf5e0',
  'badge-waiting-text': '#996800',
  'badge-active-bg': '#e0f5ec',
  'badge-active-text': '#00884c',
  'badge-completed-bg': '#f0ede8',
  'badge-completed-text': '#8a8070',
  'surrogate-bg': '#e0f5f0',
  'surrogate-text': '#006644',
  'surrogate-border': '#b8dcd0',
  'contributor-bg': '#ede8f4',
  'contributor-text': '#5a4080',
  'contributor-border': '#c8b8e0',
  'own-msg-bg': '#fdf5e0',
  'other-msg-bg': '#faf7f0',
  'grid-line': 'rgba(120,90,30,0.04)',
  'scan-line': 'rgba(0,0,0,0.015)',
  'vignette': 'rgba(0,0,0,0.06)',
  'data-readout-bg': 'rgba(200,146,0,0.06)',
};

/** Convert theme map to CSS custom property declarations for :root */
export function themeToCSS(theme: Record<string, string>): string {
  return Object.entries(theme)
    .map(([key, value]) => `--c-${key}: ${value};`)
    .join('\n  ');
}
